### ISSUE TITLE
[discussion] Should we convert from CJS to ESM?

### ISSUE THREAD

**Issue by shadowgate15** [breejs/bree#107]
I know that many package developers/maintainers are making the switch from CJS to ESM. Do we think it is time for us to make that switch?

**Comment by Spence-S** [comment]
I don't think its wise. I'd prefer to have the most broad support for users, which is still common js. 
see https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

**Comment by phanngl** [comment]
I've been trying to use Bree with a toy project using ESM. Everything seems normal so far, but my .mjs job file won't load with root option. I've been working around that by importing my job as a function.

Here's the error log : 
```
Error: Cannot find module '/Users/phanngl/projects/wwatcherbot/src/jobs'
Require stack:
- /Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/internal/source.js
- /Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/threads/index.js
- /Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/bthreads.js
- /Users/phanngl/projects/wwatcherbot/node_modules/bree/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object._require [as require] (/Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/internal/source.js:86:10)
    at Object.exports.require (/Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/threads/index.js:56:33)
    at new Bree (/Users/phanngl/projects/wwatcherbot/node_modules/bree/lib/index.js:200:37)
    at file:///Users/phanngl/projects/wwatcherbot/src/wwatcherbot.mjs:9:14
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/internal/source.js',
    '/Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/threads/index.js',
    '/Users/phanngl/projects/wwatcherbot/node_modules/bthreads/lib/bthreads.js',
    '/Users/phanngl/projects/wwatcherbot/node_modules/bree/lib/index.js'
  ]
}
```

**Comment by shadowgate15** [comment]
@phanngl this is likely an issue with how node workers handles that. I would look thru their issues and docs.

**Comment by meglio** [comment]
While you're on this, also please make sure it works with Yarn's "zero-installs" - there is no "node_modules" folder in that case, and calling `yarn jobs` proxies module resolution. So it's important to make sure the module resulution works in jobs that run in workers.

**Comment by niftylettuce** [comment]
Not going to convert this, perhaps in the future
