### ISSUE TITLE
Job cannot be added with same name immediately after it has just been removed

### ISSUE THREAD

**Issue by sorsaffari** [breejs/bree#113]
```js
bree.add({ name: 'foo', date: moment().add(1, 'm').toDate() })
bree.remove('foo')
bree.add({ name: 'foo', date: moment().add(2, 'm').toDate() })
```

running the code above throws the following error:

```shell
Error: Job #1 has a duplicate job name of foo
    at validateJobName (/Users/soroushsaffari/work/forks/express-example/node_modules/bree/lib/job-validator.js:198:17)
    at validate (/Users/soroushsaffari/work/forks/express-example/node_modules/bree/lib/job-validator.js:205:16)
    at Bree.add (/Users/soroushsaffari/work/forks/express-example/node_modules/bree/lib/index.js:647:13)
```

as a workaround, for the time being, I had to run the second call of `bree.add` after some delay (using `setTimeout`).

**Comment by mkondel** [comment]
I am having the same issue. Maybe bree.remove() should return a promise for when it has completed its work. Would it make sense to change its code like so?
```javascript
  async remove(name) {
    const job = this.config.jobs.find((j) => j.name === name);
    if (!job) {
      throw new Error(`Job "${name}" does not exist`);
    }
    
    // update the jobs array 1st, then call this.stop()
    this.config.jobs = this.config.jobs.filter((j) => j.name !== name);

    // make sure it also closes any open workers
    // return the promise so that client code can await for it
    return this.stop(name);
  }
```

**Comment by sorsaffari** [comment]
thanks @mkondel, that was it!
