### ISSUE TITLE
Can't Set L in Cron. had an invalid cron pattern: Element 'L of daysOfMonth field is invalid. (Input cron: '30 18 L * *')

### ISSUE THREAD

**Issue by DynamiteC** [breejs/bree#135]
Getting Above Error While Setting up Cron Job for Last Day of month at 6:30pm time. As per the guidelines the cron is supported. 

```js
    // runs `./jobs/worker-11.js` at midnight on the last day of month
    {
      name: 'worker-11',
      cron: '0 0 L * *'
    },
```

I got referenced from above, how to resolve this. 

This is my code.

```js
const bree = new Bree({
  logger,
  jobs: [{
    name: 'testJob',
    cron: '30 18 L * *'
  }]
});
```
This is the full error. 
```sh
Error: Job #1 named "testJob" had an invalid cron pattern: Element 'L of daysOfMonth field is invalid. (Input cron: '30 18 L * *')
    at validateCron (/home/user/project/node_modules/bree/lib/job-validator.js:175:23)
    at validate (/home/user/project/node_modules/bree/lib/job-validator.js:265:64)
    at Bree.init (/home/user/project/node_modules/bree/lib/index.js:261:11)
    at new Bree (/home/user/project/node_modules/bree/lib/index.js:193:11)
    at Object.<anonymous> (/home/user/project/crons/test-job.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**Comment by shadowgate15** [comment]
add
```js
      cronValidate: {
        override: {
          useLastDayOfWeek: true
        }
      }
```
to your job configuration. Will be adding this to the docs thanks for catching it.

**Comment by DynamiteC** [comment]
Thanks!!

**Comment by DynamiteC** [comment]
@shadowgate15 @niftylettuce Hi, This still didnt workout. 

I tried both ways
```JS
    cron: '30 18 L * *',
    cronValidate: {
      useLastDayOfMonth: true
    }
```
as well as 
```JS
    cron: '30 18 L * *',
    cronValidate: {
      override: {
        useLastDayOfMonth: true
      }
    }
```
It shows same error. 
```Sh
Error: Job #1 named "testJob" had an invalid cron pattern: Element 'L of daysOfMonth field is invalid. (Input cron: '30 18 L * *')
```

**Comment by shadowgate15** [comment]
Just to confirm, which version of Bree are you using?

**Comment by DynamiteC** [comment]
I have found a workaround this. 

```JS
hasSeconds: true,
cronValidate: {
   override: {
        useLastDayOfMonth: true
      }
    }
```
