### ISSUE TITLE
jobs/index.js as an ESM module

### ISSUE THREAD

**Issue by maxpain** [breejs/bree#180]
Hello. Bree should use `import` instead of `require` for `jobs/index.js` as an ESM module.

jobs/index.js:
```javascript
const jobs = ['job'];
export default jobs;
```

Error:
```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/maxpain/dev/fastcup/backend/cron/.build/jobs/index.js from /Users/maxpain/dev/fastcup/backend/cron/node_modules/bree/src/index.js not supported.
Instead change the require of /Users/maxpain/dev/fastcup/backend/cron/.build/jobs/index.js in /Users/maxpain/dev/fastcup/backend/cron/node_modules/bree/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Bree.init (/Users/maxpain/dev/fastcup/backend/cron/node_modules/bree/src/index.js:207:28)
    at new Bree (/Users/maxpain/dev/fastcup/backend/cron/node_modules/bree/src/index.js:172:10)
    at file:///Users/maxpain/dev/fastcup/backend/cron/.build/index.js:17:14
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by maxpain** [comment]
Thanks!
