### ISSUE TITLE
Intervals created with `later` are not accepted

### ISSUE THREAD

**Issue by adrfantini** [breejs/bree#78]
Hi! The documentation states that i can pass as `interval`:

> Object values must be a `later` schedule object value (e.g. `later.schedule(later.parse.cron('15 10 * * ? *'))`)

However, this throws an error:
```
later = require('later')
const textSched = later.parse.text('every 5 sec');

const Bree = require('bree')
const bree = new Bree({
    jobs : [
        {
            name : 'myJob',
            interval : later.schedule(textSched)
        }
    ]
})
bree.start()
```
The error is:
```
Uncaught Error: Job #1 named "myJob" had an invalid interval of undefined
    at /usr/lib/node_modules/bree/lib/job-validator.js:214:36
    at Array.forEach (<anonymous>)
    at validate (/usr/lib/node_modules/bree/lib/job-validator.js:209:27)
    at new Bree (/usr/lib/node_modules/bree/lib/index.js:223:9)
    at repl:1:14
    at Script.runInThisContext (vm.js:120:20)
    at REPLServer.defaultEval (repl.js:430:29)
    at bound (domain.js:426:14)
    at REPLServer.runBound [as eval] (domain.js:439:12)
    at REPLServer.onLine (repl.js:758:10)

Error: Value [object Object] must be a finite number >= 0 or a String parseable by `later.parse.text` (see <https://breejs.github.io/later/parsers.html#text> for examples)
    at parseValue (/usr/lib/node_modules/bree/lib/job-utils.js:76:51)
    at /usr/lib/node_modules/bree/lib/job-validator.js:212:9
    at Array.forEach (<anonymous>)
    at validate (/usr/lib/node_modules/bree/lib/job-validator.js:209:27)
    at new Bree (/usr/lib/node_modules/bree/lib/index.js:223:9)
    at repl:1:14
    at Script.runInThisContext (vm.js:120:20)
    at REPLServer.defaultEval (repl.js:430:29)
    at bound (domain.js:426:14)
    at REPLServer.runBound [as eval] (domain.js:439:12)
```

I am using `bree 4.1.0` and `node 12.16.1`.

**Comment by niftylettuce** [comment]
I think the docs need updated so that we don't recommend wrapping with `later.schedule`, instead it should just be like this without it: <https://github.com/breejs/bree/blob/master/test/test.js#L262-L267>

Care to make a PR?

**Comment by adrfantini** [comment]
Things are not really clear for me.
So schedules created e.g. with `later.recur` are not supported anymore?

**Comment by niftylettuce** [comment]
Schedules are supported, you just don't wrap with `later.schedule`.  https://github.com/breejs/bree/commit/83e726f7f9b336c1d57d91ae01978f1ea185193e

**Comment by niftylettuce** [comment]
Don't wrap with `later.schedule` basically and you're good.

**Comment by niftylettuce** [comment]
https://github.com/breejs/bree/commit/ac28cf6b6bafb97a9196a3a236d40e7e3b0b5d73

**Comment by adrfantini** [comment]
Oh, I see. Thanks!
